# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 18:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_article_shortcontent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='shortContent',
            new_name='short_сontent',
        ),
    ]
