# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 10:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20161115_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='short_сontent',
            new_name='short_content',
        ),
    ]
